### ISSUE TITLE
Not able to query at the time of querying

### ISSUE THREAD

**Issue by Harsh00988** [rombru/mongodb_layer#1]
How do we query and what steps do we follow to get the data that satisfies the query results? Is there in specific format for the query? If yes, please help me with format.

**Comment by rombru** [comment]
Hello, thanks for using the plugin!

Once the plugin is installed, you can use the plugin button to show its UI.
Then, you fill the connection string after clicking on the "Connect" button.
It should automatically show you the databases

Then, you select a database, collection, geometry field and its format.
All the dropdowns should be prefilled automatically.

The query format is exactly the same as you would use in a tool like MongoDB Compass (e.g. { "property1":"myvalue"} )
When you will click on "Add layer", the data will be loaded automatically in a new layer

**Comment by Harsh00988** [comment]
Thank you @rombru. I was able to make the query successfully. Initially I was trying to enter the whole mongodb query.
